# Generated by Django 4.2 on 2024-07-21 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makedeposit', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepositLog',
        ),
    ]
