# Generated by Django 4.2 on 2024-04-16 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openaccount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(default=openaccount.models.generate_unique_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(default=0.0)),
                ('pin', models.CharField(max_length=4)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
