# Generated by Django 4.2 on 2024-05-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transfer_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(editable=False, max_length=8)),
                ('recepient', models.CharField(editable=False, max_length=8)),
                ('amount', models.FloatField(editable=False)),
            ],
        ),
    ]
