# Generated by Django 4.2 on 2024-05-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openaccount', '0002_transfer_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_logs',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transfer_logs',
            name='recepient',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='transfer_logs',
            name='sender',
            field=models.CharField(max_length=8),
        ),
    ]
