# Generated by Django 4.2 on 2024-06-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openaccount', '0003_alter_transfer_logs_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=8)),
                ('amount', models.FloatField()),
                ('redeemed', models.BooleanField(default=False)),
                ('coupon_code', models.CharField(default=None, max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
