# Generated by Django 4.2 on 2024-07-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openaccount', '0005_alter_withdrawallog_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawallog',
            name='coupon_code',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
