# Generated by Django 4.2 on 2024-07-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openaccount', '0007_depositlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositlog',
            name='code',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
