# Generated by Django 4.2 on 2024-07-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openaccount', '0009_alter_depositlog_depositor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositlog',
            name='amount',
            field=models.FloatField(default=None),
        ),
    ]
