# Generated by Django 4.2 on 2024-08-21 15:51

from django.db import migrations, models
import openaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('openaccount', '0010_alter_depositlog_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositlog',
            name='depositor_last_name',
            field=models.CharField(default='', max_length=50, validators=[openaccount.models.min_name_length]),
        ),
    ]
