# Generated by Django 4.2 on 2024-08-21 15:52

from django.db import migrations, models
import openaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('openaccount', '0011_alter_depositlog_depositor_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositlog',
            name='depositor_last_name',
            field=models.CharField(max_length=50, validators=[openaccount.models.min_name_length]),
        ),
    ]
