# Generated by Django 4.2 on 2024-08-20 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payment_API.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EpaymentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default=payment_API.models.keyGenerator, max_length=50, unique=True)),
                ('entity_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('user_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
