# Generated by Django 4.2 on 2024-08-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epaymentsubscription',
            name='user_entity',
        ),
        migrations.AddField(
            model_name='epaymentsubscription',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
