# Generated by Django 4.2 on 2024-09-06 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_API', '0002_remove_epaymentsubscription_user_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epaymentsubscription',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='epaymentsubscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 20, 49, 50, 173127)),
        ),
    ]
