# Generated by Django 4.2 on 2024-09-25 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openaccount', '0012_alter_depositlog_depositor_last_name'),
        ('payment_API', '0004_alter_epaymentsubscription_price_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epaymentsubscription',
            name='merchant_account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='openaccount.account'),
        ),
    ]
