# Generated by Django 4.2 on 2024-09-25 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_API', '0005_epaymentsubscription_merchant_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=30)),
                ('transaction_id_client', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('merchant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment_API.epaymentsubscription')),
            ],
        ),
    ]
