# Generated by Django 4.2 on 2024-09-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_API', '0007_paymentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_detail',
            name='transaction_id_client',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
