# Generated by Django 4.2 on 2024-09-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openaccount', '0012_alter_depositlog_depositor_last_name'),
        ('payment_API', '0008_alter_transaction_detail_transaction_id_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epaymentsubscription',
            name='merchant_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openaccount.account'),
        ),
    ]
