# Generated by Django 4.2 on 2024-09-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_API', '0009_alter_epaymentsubscription_merchant_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentLog',
        ),
    ]
