# Generated by Django 4.2 on 2024-09-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_API', '0011_paymentlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentLog',
        ),
    ]
