# Generated by Django 4.2 on 2024-09-30 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openaccount', '0012_alter_depositlog_depositor_last_name'),
        ('payment_API', '0013_paymentlogging'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlogging',
            name='p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='openaccount.account'),
        ),
    ]
