# Generated by Django 4.2 on 2024-09-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_API', '0014_paymentlogging_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentlogging',
            old_name='p',
            new_name='client',
        ),
    ]
