# Generated by Django 4.2 on 2024-10-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_API', '0015_rename_p_paymentlogging_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_detail',
            name='callback_code',
            field=models.CharField(default='None', max_length=16),
        ),
        migrations.AddField(
            model_name='transaction_detail',
            name='callback_url',
            field=models.TextField(default='None'),
        ),
    ]
