# Generated by Django 4.2 on 2024-10-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_API', '0016_transaction_detail_callback_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_detail',
            name='callback_code',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction_detail',
            name='callback_url',
            field=models.TextField(),
        ),
    ]
