# Generated by Django 4.2 on 2026-03-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_API', '0017_alter_transaction_detail_callback_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_detail',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
