# Generated by Django 4.2 on 2026-03-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_API', '0018_transaction_detail_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_detail',
            name='client_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction_detail',
            name='transaction_id_client',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
